### ISSUE TITLE
Can't load embed with ecto_sqlite3 adapter

### ISSUE THREAD

**Issue by rupurt** [mathieuprog/polymorphic_embed#39]
Howdy,

Thank you for the fantastic library!

I'm trying to use it with the new [SQLite3 ecto adapter](https://github.com/elixir-sqlite/ecto_sqlite3) and I'm running into an error loading the embed after a successful save.

```
** (FunctionClauseError) no function clause matching in PolymorphicEmbed.do_get_polymorphic_module_from_map/3
     
          The following arguments were given to PolymorphicEmbed.do_get_polymorphic_module_from_map/3:
          
              # 1
              "{\"last_received_at\":\"2021-05-01T21:47:26.360911Z\",\"last_venue_timestamp\":\"2021-05-01T21:47:26.360906Z\",\"venue_order_id\":\"9e7b5696-b6fe-4f89-b348-f89369456c55\",\"__type__\":\"accept_create\"}"
          
              # 2
              "__type__"
          
              # 3
              [%{identify_by_fields: [], module: Tai.NewOrders.Transitions.CreateError, type: "create_error"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.AcceptCreate, type: "accept_create"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.Open, type: "open"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.PendCancel, type: "pend_cancel"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.AcceptCancel, type: "accept_cancel"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.CancelError, type: "cancel_error"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.Cancel, type: "cancel"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.PendAmend, type: "pend_amend"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.AcceptAmend, type: "accept_amend"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.AmendError, type: "amend_error"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.Amend, type: "amend"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.Fill, type: "fill"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.PartialFill, type: "partial_fill"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.Expire, type: "expire"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.Reject, type: "reject"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.Skip, type: "skip"}]
          
          Attempted function clauses (showing 1 out of 1):
          
              defp do_get_polymorphic_module_from_map(%{} = attrs, type_field, types_metadata)
          
          stacktrace:
            (polymorphic_embed 1.3.4) lib/polymorphic_embed.ex:260: PolymorphicEmbed.do_get_polymorphic_module_from_map("{\"last_received_at\":\"2021-05-01T21:47:26.360911Z\",\"last_venue_timestamp\":\"2021-05-01T21:47:26.360906Z\",\"venue_order_id\":\"9e7b5696-b6fe-4f89-b348-f89369456c55\",\"__type__\":\"accept_create\"}", "__type__", [%{identify_by_fields: [], module: Tai.NewOrders.Transitions.CreateError, type: "create_error"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.AcceptCreate, type: "accept_create"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.Open, type: "open"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.PendCancel, type: "pend_cancel"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.AcceptCancel, type: "accept_cancel"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.CancelError, type: "cancel_error"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.Cancel, type: "cancel"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.PendAmend, type: "pend_amend"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.AcceptAmend, type: "accept_amend"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.AmendError, type: "amend_error"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.Amend, type: "amend"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.Fill, type: "fill"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.PartialFill, type: "partial_fill"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.Expire, type: "expire"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.Reject, type: "reject"}, %{identify_by_fields: [], module: Tai.NewOrders.Transitions.Skip, type: "skip"}])
            (polymorphic_embed 1.3.4) lib/polymorphic_embed.ex:222: PolymorphicEmbed.load/3
            (ecto 3.6.1) lib/ecto/type.ex:894: Ecto.Type.process_loaders/3
            (ecto 3.6.1) lib/ecto/repo/queryable.ex:406: Ecto.Repo.Queryable.struct_load!/6
            (ecto 3.6.1) lib/ecto/repo/queryable.ex:238: anonymous fn/5 in Ecto.Repo.Queryable.preprocessor/3
            (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
            (ecto 3.6.1) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
            (ecto 3.6.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
            (tai 0.0.65) lib/tai/commander.ex:117: Tai.Commander.handle_call/3
            (stdlib 3.14.2) gen_server.erl:715: :gen_server.try_handle_call/4
            (stdlib 3.14.2) gen_server.erl:744: :gen_server.handle_msg/6
            (stdlib 3.14.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
     
     stacktrace:
       (elixir 1.11.4) lib/gen_server.ex:1027: GenServer.call/3
       (tai 0.0.65) lib/tai/iex/commands/order_transitions.ex:18: Tai.IEx.Commands.OrderTransitions.order_transitions/1
       (ex_unit 1.11.4) lib/ex_unit/capture_io.ex:191: ExUnit.CaptureIO.do_capture_gl/2
       (ex_unit 1.11.4) lib/ex_unit/capture_io.ex:149: ExUnit.CaptureIO.do_capture_io/3
       test/tai/iex/commands/order_transitions_test.exs:52: (test)
```

I'm not super familiar with the requirements of ecto adapters but the crux of the issue is that the SQLite adapter is returning a string for the `map` field and `polymorphic_embed` expects that to already be turned into an Elixir map. I'm not sure if this is something wrong in `ecto_sqlite3` or does `polymorphic_embed` need to call the currently [ignored loader](https://github.com/mathieuprog/polymorphic_embed/blob/master/lib/polymorphic_embed.ex#L210)?

```elixir
def load(data, _loader, %{types_metadata: types_metadata, type_field: type_field}) do
  case do_get_polymorphic_module_from_map(data, type_field, types_metadata) do
    nil -> raise_cannot_infer_type_from_data(data)
    module when is_atom(module) -> {:ok, Ecto.embedded_load(module, data, :json)}
  end
end
```

This is the migration

```elixir
defmodule Tai.NewOrders.OrderRepo.Migrations.CreateOrderTransitions do
  use Ecto.Migration

  def change do
    create table(:order_transitions, primary_key: false) do
      add(:id, :uuid, null: false, primary_key: true)
      add(:order_client_id, references(:orders, column: :client_id, type: :uuid))
      add(:transition, :map, null: false)

      timestamps()
    end
  end
end

```

And schema definition

```elixir
defmodule Tai.NewOrders.OrderTransition do
  use Ecto.Schema
  import Ecto.Changeset
  import PolymorphicEmbed, only: [cast_polymorphic_embed: 3]
  alias Tai.NewOrders.{Order, Transitions}

  @type client_id :: Ecto.UUID.t()
  @type t :: %__MODULE__{}

  @primary_key {:id, Ecto.UUID, autogenerate: true}
  @timestamps_opts [autogenerate: {Tai.DateTime, :timestamp, []}, type: :utc_datetime_usec]

  schema "order_transitions" do
    belongs_to(:order, Order, source: :order_client_id, references: :client_id, foreign_key: :order_client_id, type: Ecto.UUID)

    field(:transition, PolymorphicEmbed,
      types: [
        create_error: Transitions.CreateError,
        accept_create: Transitions.AcceptCreate,
        open: Transitions.Open,
        pend_cancel: Transitions.PendCancel,
        accept_cancel: Transitions.AcceptCancel,
        cancel_error: Transitions.CancelError,
        cancel: Transitions.Cancel,
        pend_amend: Transitions.PendAmend,
        accept_amend: Transitions.AcceptAmend,
        amend_error: Transitions.AmendError,
        amend: Transitions.Amend,
        fill: Transitions.Fill,
        partial_fill: Transitions.PartialFill,
        expire: Transitions.Expire,
        reject: Transitions.Reject,
        skip: Transitions.Skip
      ],
      on_type_not_found: :raise,
      on_replace: :update
    )

    timestamps()
  end

  @doc false
  def changeset(order_transition, attrs) do
    order_transition
    |> cast(attrs, [:order_client_id])
    |> cast_polymorphic_embed(:transition, required: true)
    |> validate_required([:order_client_id])
  end
end
```

**Comment by mathieuprog** [comment]
Ideally we should first check if it's an issue with the sqlite3 adapter.
I would first try to code a very simple custom Ecto type that just wraps a map, and test the difference with Postgres and Sqlite3. Report any difference to the sqlite3 maintainers. Would you have time to do these tests first?

**Comment by rupurt** [comment]
Sure thing. I'll try it out on the Postgres adapter.

**Comment by rupurt** [comment]
The Postgres adapter is returning a map. I'll open up an issue on the SQLite3 repo and link this issue

**Comment by mathieuprog** [comment]
Can you try the code in master?
```
     {:polymorphic_embed, git: "git://github.com/mathieuprog/polymorphic_embed.git",
             branch: "master",
             override: true},
```

**Comment by rupurt** [comment]
Works great @mathieuprog. Cheers :beers:

**Comment by rupurt** [comment]
@mathieuprog when you get a chance do you mind cutting a new release with this?

**Comment by mathieuprog** [comment]
Done 1.7.0
